import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Rnd } from 'react-rnd'
import { Archive, Briefcase, Camera, ChevronRight, Clock3, Download, Folder, Gamepad2, Globe, HardDrive, HelpCircle, LockKeyhole, Mail, Maximize2, Menu, MessageSquare, Minimize2, Monitor, Power, RefreshCw, Search, Server, ShoppingBag, Terminal as TerminalIcon, Trash2, UserCircle, Volume2, Wifi, X } from 'lucide-react'
import heroImg from './assets/hero.png'
import useSessionStore from './store/useSessionStore'
import './App.css'

const APPS = [
  { id: 'resume', title: 'My Resume', icon: Briefcase, keywords: 'cv pdf experience', color: '#dba86a' },
  { id: 'browser', title: 'Browser', icon: Globe, keywords: 'google web search', color: '#72b7aa' },
  { id: 'terminal', title: 'Windows Terminal', icon: TerminalIcon, keywords: 'cli commands', color: '#9bbed2' },
  { id: 'work', title: 'My Work', icon: Folder, keywords: 'projects github websites ai', color: '#d8be77' },
  { id: 'store', title: 'Store', icon: ShoppingBag, keywords: 'apps marketplace tools', color: '#d77b72' },
  { id: 'hobbies', title: 'My Hobbies', icon: Gamepad2, keywords: 'interests music games', color: '#bd9bd4' },
  { id: 'computer', title: 'My Computer', icon: HardDrive, keywords: 'files drives folders pc', color: '#82a7ca' },
  { id: 'recycle', title: 'Recycling Bin', icon: Trash2, keywords: 'deleted bin', color: '#a4b6a1' },
  { id: 'mail', title: 'Mail (Contact)', icon: Mail, keywords: 'contact message email', color: '#e29b76' },
  { id: 'clock', title: 'Clock', icon: Clock3, keywords: 'time ist', color: '#e6c36d' },
  { id: 'gallery', title: 'Gallery', icon: Camera, keywords: 'photos memories images', color: '#81b7c2' },
]

const PROJECTS = [
  { name: 'Portfolio OS', type: 'Websites', description: 'A playful Windows-inspired portfolio experience.', repo: 'Portfolio' },
  { name: 'AI Experiments', type: 'AI Projects', description: 'Small, curious tools exploring practical AI interfaces.', repo: 'AI-Projects' },
  { name: 'Frontend Lab', type: 'Projects', description: 'Focused experiments in interaction, motion, and accessibility.', repo: 'Frontend-Projects' },
]

function istTime(date) { return date.toLocaleTimeString('en-IN', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', hour12: true }) }
function istDate(date) { return date.toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) }

function LoginFlow({ onDesktop }) {
  const setVisitor = useSessionStore((state) => state.setVisitor)
  const visitor = useSessionStore((state) => state.visitor)
  const [stage, setStage] = useState('lock')
  const [name, setName] = useState(visitor)
  const [password, setPassword] = useState('')
  const [error, setError] = useState(false)
  const [now, setNow] = useState(new Date())
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer) }, [])
  useEffect(() => { if (stage !== 'lock') return undefined; const next = () => setStage('identify'); window.addEventListener('keydown', next); return () => window.removeEventListener('keydown', next) }, [stage])
  const submitName = (event) => { event.preventDefault(); if (name.trim()) { setVisitor(name.trim()); setStage('login') } }
  const submitPassword = (event) => { event.preventDefault(); if (password === 'vidhitam') { setError(false); setStage('transition'); setTimeout(onDesktop, 2100) } else { setError(true); setPassword('') } }
  return <AnimatePresence mode="wait">
    {stage === 'lock' && <motion.section className="lock-screen screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setStage('identify')}><div className="video-placeholder"><img src={heroImg} alt="Abstract portfolio background" /><div className="scan-lines" /></div><div className="lock-shade" /><div className="lock-content"><p className="eyebrow">PORTFOLIO OS / SECURE SESSION</p><div className="lock-time">{istTime(now)}</div><div className="lock-date">{istDate(now)}</div><p className="continue-hint">Click anywhere or press any key to continue</p></div></motion.section>}
    {stage === 'identify' && <motion.section className="center-screen screen" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}><div className="dialog-window"><p className="window-kicker">VISITOR IDENTIFICATION</p><h1>Who is viewing this portfolio?</h1><p className="muted">Your name will be remembered for this session.</p><form onSubmit={submitName}><label htmlFor="visitor-name">Your name</label><input id="visitor-name" autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Type your name" /><button type="submit">Continue <ChevronRight size={16} /></button></form></div></motion.section>}
    {stage === 'login' && <motion.section className="center-screen screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="login-window"><div className="avatar"><Monitor size={30} /></div><p className="window-kicker">WELCOME BACK, {name.toUpperCase()}</p><h1>It's you Stalker</h1><form onSubmit={submitPassword}><label htmlFor="password">Password</label><input id="password" autoFocus type="password" value={password} onChange={(event) => { setPassword(event.target.value); setError(false) }} placeholder="Enter password" /><p className="password-hint">Password: vidhitam</p>{error && <motion.p className="error-message" initial={{ x: -8 }} animate={{ x: [8, -8, 5, -5, 0] }}>whaa!!</motion.p>}<button type="submit">Sign in</button></form></div></motion.section>}
    {stage === 'transition' && <motion.section className="transition-screen screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.img src={heroImg} alt="Portfolio logo" initial={{ scale: .45, opacity: 0 }} animate={{ scale: 1.3, opacity: 1 }} transition={{ duration: 2 }} /><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }}>Starting your session...</motion.p></motion.section>}
  </AnimatePresence>
}

function AppWindow({ app, index, minimized, maximized, onFocus, onMinimize, onMaximize, onClose, children }) {
  const Icon = app.icon
  return <Rnd className={`app-window ${minimized ? 'window-hidden' : ''} ${maximized ? 'window-maximized' : ''}`} default={{ x: 110 + index * 28, y: 70 + index * 22, width: 620, height: 450 }} size={maximized ? { width: '100%', height: 'calc(100% - 58px)' } : undefined} position={maximized ? { x: 0, y: 0 } : undefined} minWidth={350} minHeight={260} bounds="parent" dragHandleClassName="window-bar" onMouseDown={onFocus} disableDragging={maximized} enableResizing={!maximized}>
    <div className="window-frame"><header className="window-bar"><span className="window-title"><Icon size={15} color={app.color} />{app.title}</span><div className="window-actions"><button title="Minimize" onClick={onMinimize}><Minimize2 size={14} /></button><button title="Maximize" onClick={onMaximize}><Maximize2 size={14} /></button><button title="Close" onClick={onClose}><X size={15} /></button></div></header><div className="window-content">{children}</div></div>
  </Rnd>
}

function Resume() { return <div className="doc-app"><div className="pdf-toolbar"><span>My_Resume.pdf</span><button onClick={() => window.print()}><Download size={15} /> Download</button></div><div className="paper"><p className="paper-label">CURRICULUM VITAE</p><h2>Vidhitam Chakole</h2><p>Creative developer crafting thoughtful digital experiences.</p><hr /><h3>Profile</h3><p>Frontend-focused builder exploring polished interfaces, useful tools, and expressive interactions.</p><h3>Skills</h3><p>React / JavaScript / Python / FastAPI / UI Engineering</p><div className="skeleton-lines" /></div></div> }
function Browser() { const [query, setQuery] = useState(''); const [url, setUrl] = useState('https://www.google.com'); const search = (event) => { event.preventDefault(); setUrl(`https://www.google.com/search?q=${encodeURIComponent(query)}`) }; return <div className="browser-app"><div className="browser-nav"><button onClick={() => setUrl('https://www.google.com')}>Back</button><input value={url} onChange={(event) => setUrl(event.target.value)} /></div><div className="browser-page"><Globe size={40} /><h2>Google</h2><form onSubmit={search}><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the web" /><button>Search</button></form><div className="search-presets"><button onClick={() => setQuery('Vidhitam Chakole GitHub')}>Vidhitam Chakole GitHub</button><button onClick={() => setQuery('Vidhitam Chakole portfolio')}>Vidhitam Chakole portfolio</button></div><p className="muted">External links open in a new tab for your safety.</p><button className="text-button" onClick={() => window.open('https://github.com/Vidhitam-chakole', '_blank', 'noopener,noreferrer')}>Visit GitHub profile</button></div></div> }
function TerminalApp() { const [lines, setLines] = useState(['Vidhitam Terminal [Version 1.0]', 'Type help to see available commands.']); const [command, setCommand] = useState(''); const run = (event) => { event.preventDefault(); const value = command.trim().toLowerCase(); const output = { help: 'help   clear   google   resume   projects', google: 'Opening the simulated browser...', resume: 'Loading My Resume...', projects: '3 projects found in My Work.' }[value] || `Command not found: ${value}`; setLines(value === 'clear' ? [] : [...lines, `visitor@portfolio> ${command}`, output]); setCommand('') }; return <div className="terminal-app"><div className="terminal-output">{lines.map((line, index) => <div key={`${line}-${index}`}>{line}</div>)}</div><form onSubmit={run}><span>visitor@portfolio&gt;</span><input autoFocus value={command} onChange={(event) => setCommand(event.target.value)} /></form></div> }
function Work() { const [filter, setFilter] = useState('All'); const items = filter === 'All' ? PROJECTS : PROJECTS.filter((project) => project.type === filter); return <div className="work-app"><div className="filter-row">{['All', 'AI Projects', 'Websites', 'Projects'].map((item) => <button className={filter === item ? 'selected' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="project-grid">{items.map((project) => <article className="project-card" key={project.name}><p>{project.type}</p><h3>{project.name}</h3><span>{project.description}</span><div><button onClick={() => window.open(`https://github.com/Vidhitam-chakole/${project.repo}`, '_blank', 'noopener,noreferrer')}>GitHub</button><button onClick={() => window.open('https://github.com/Vidhitam-chakole', '_blank', 'noopener,noreferrer')}>Live Demo</button></div></article>)}</div></div> }
function Store() { return <div className="store-app"><p className="window-kicker">FEATURED COLLECTION</p><h2>Tools made with curiosity.</h2><div className="store-list">{['Portfolio OS', 'Prompt Playground', 'Motion Kit'].map((item, index) => <div key={item}><span className="store-icon">{index === 0 ? <Monitor /> : index === 1 ? <MessageSquare /> : <Archive />}</span><span><strong>{item}</strong><small>Available in this collection</small></span><button>View</button></div>)}</div></div> }
function Hobbies() { return <div className="hobby-grid">{[['Music', 'Finding rhythm in focused work', '♫'], ['Gaming', 'Systems, stories, and playful worlds', '▣'], ['Photography', 'Collecting small visual details', '◉']].map(([title, text, mark]) => <article key={title}><b>{mark}</b><h3>{title}</h3><p>{text}</p></article>)}</div> }
function Computer() { return <div className="computer-app"><h2>This PC</h2><p className="muted">Folders and drives</p><div className="drive-grid"><div><HardDrive /><strong>Local Disk (C:)</strong><small>Portfolio system</small></div><div><Folder /><strong>Documents</strong><small>12 items</small></div><div><Folder /><strong>Projects</strong><small>3 items</small></div><div><Server /><strong>Network</strong><small>Connected</small></div></div></div> }
function Recycle({ visitor }) { return <div className="recycle-app"><Trash2 size={45} /><h2>Nothing to see here, {visitor}.</h2><p>The recycling bin is empty. Even the mistakes were shipped back.</p></div> }
function MailApp() { const [sent, setSent] = useState(''); const send = (event) => { event.preventDefault(); setSent('msg nhi gaya') }; return <div className="mail-app"><h2>Send a message</h2><form onSubmit={send}><label htmlFor="contact-name">Name</label><input id="contact-name" name="name" required maxLength="80" placeholder="Your name" /><label htmlFor="contact-message">Message</label><textarea id="contact-message" name="message" required maxLength="2000" placeholder="Say hello" rows="4" /><button type="submit"><Mail size={15} /> Send message</button></form>{sent && <p className="sent-message">{sent}</p>}<p className="muted">ruko jara hai msg · aajayega tode der me reply</p></div> }
function ClockApp({ now }) { return <div className="clock-app"><p className="window-kicker">INDIAN STANDARD TIME</p><div>{istTime(now)}</div><span>{istDate(now)}</span></div> }
function Gallery() { return <div className="gallery-app"><div className="gallery-hero"><Camera size={28} /><span>Photo memories</span></div><div className="gallery-squares"><i /><i /><i /><i /></div><p className="muted">Gallery ready for your photo assets.</p></div> }

function Desktop({ onLock }) {
  const visitor = useSessionStore((state) => state.visitor)
  const [now, setNow] = useState(new Date()); const [open, setOpen] = useState([]); const [minimized, setMinimized] = useState([]); const [maximized, setMaximized] = useState([]); const [active, setActive] = useState(''); const [start, setStart] = useState(false); const [query, setQuery] = useState(''); const [clicks, setClicks] = useState(0); const [egg, setEgg] = useState(false)
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer) }, [])
  const results = useMemo(() => APPS.filter((app) => `${app.title} ${app.keywords}`.toLowerCase().includes(query.toLowerCase())), [query])
  const launch = (id) => { setOpen((items) => items.includes(id) ? items : [...items, id]); setMinimized((items) => items.filter((item) => item !== id)); setActive(id); setStart(false) }
  const power = (action) => { setStart(false); if (action === 'Lock' || action === 'Restart') onLock() }
  const openApp = (app) => <AppWindow app={app} index={open.indexOf(app.id)} minimized={minimized.includes(app.id)} maximized={maximized.includes(app.id)} onFocus={() => setActive(app.id)} onMinimize={() => setMinimized((items) => [...items, app.id])} onMaximize={() => setMaximized((items) => items.includes(app.id) ? items.filter((item) => item !== app.id) : [...items, app.id])} onClose={() => { setOpen((items) => items.filter((item) => item !== app.id)); setActive('') }}>{app.id === 'resume' ? <Resume /> : app.id === 'browser' ? <Browser /> : app.id === 'terminal' ? <TerminalApp /> : app.id === 'work' ? <Work /> : app.id === 'store' ? <Store /> : app.id === 'hobbies' ? <Hobbies /> : app.id === 'computer' ? <Computer /> : app.id === 'recycle' ? <Recycle visitor={visitor} /> : app.id === 'mail' ? <MailApp /> : app.id === 'clock' ? <ClockApp now={now} /> : <Gallery />}</AppWindow>
  return <motion.section className="desktop screen" initial={{ opacity: 0 }} animate={{ opacity: 1 }} onClick={() => { const count = clicks + 1; setClicks(count); if (count >= 4) { setEgg(true); setClicks(0) } }}><div className="desktop-wallpaper"><div className="desktop-title"><span>Vidhitam</span><strong>Creative developer</strong></div><div className="desktop-icons">{APPS.map((app) => { const Icon = app.icon; return <button key={app.id} onDoubleClick={(event) => { event.stopPropagation(); launch(app.id) }}><Icon size={30} color={app.color} /><span>{app.title}</span></button> })}</div></div>{open.map((id) => openApp(APPS.find((app) => app.id === id)))}<footer className="taskbar"><button className="start-button" onClick={(event) => { event.stopPropagation(); setStart(!start) }}><Menu size={19} /> Start</button>{open.map((id) => { const app = APPS.find((item) => item.id === id); return <button className={`taskbar-app ${active === id ? 'active' : ''}`} key={id} onClick={(event) => { event.stopPropagation(); launch(id) }}><app.icon size={17} /> {app.title}</button> })}<div className="taskbar-spacer" /><Wifi size={16} /><Volume2 size={16} /><div className="taskbar-time">{istTime(now)}<small>{now.toLocaleDateString('en-IN')}</small></div></footer>{start && <div className="start-menu" onClick={(event) => event.stopPropagation()}><div className="profile"><UserCircle size={26} /><span>{visitor || 'Visitor'}<small>Portfolio session</small></span><Power size={18} onClick={() => power('Shut down')} /></div><div className="start-search"><Search size={16} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search apps" /></div><p className="pinned-label">{query ? 'Search results' : 'Pinned'}</p><div className="pinned-grid">{results.map((app) => { const Icon = app.icon; return <button key={app.id} onClick={() => launch(app.id)}><Icon size={22} color={app.color} /><span>{app.title}</span></button> })}</div><div className="power-row"><button onClick={() => power('Lock')}><LockKeyhole size={15} /> Lock</button><button onClick={() => power('Restart')}><RefreshCw size={15} /> Restart</button><button onClick={() => power('Shut down')}><Power size={15} /> Shut down</button></div></div>}{egg && <motion.div className="easter-egg" initial={{ scale: .8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><HelpCircle size={25} /><div><strong>Hey {visitor}!</strong><p>You found the fourth wall. Welcome to the good part.</p></div><button onClick={() => setEgg(false)}><X size={16} /></button></motion.div>}</motion.section>
}

function App() { const [mode, setMode] = useState('auth'); return <main className="app-shell">{mode === 'auth' ? <LoginFlow onDesktop={() => setMode('desktop')} /> : <Desktop onLock={() => setMode('auth')} />}</main> }
export default App
